config/routes.rb
Rails.application.routes.draw do
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    @flats = Flat.all
  end

  def show
    @flat = Flat.find(params[:id])
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    if @flat.save
      redirect_to restaurant_path
    else
      render :new
    end
  end

  def edit

  end

  def update
  end

  def destroy
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<% @flats.each do |flat| %>
  <h2><%= link_to flat.name, flat_path(flat) %></h2>
  <p><%= flat.address %></p>
  <p><%= flat.description %></p>
  <span><%= flat.price_per_night %></span>
  <span><%= flat.number_of_guests %></span>
<% end %>

app/views/flats/new.html.erb
<%= simple_form_for @flat do |f|  %>
  <%= f.input :name, class: "form-control"%>
  <%= f.input :address  %>
  <%= f.input :description  %>
  <%= f.input :price_per_night  %>
  <%= f.input :number_of_guests  %>
  <%= f.submit "Submit", class: "btn btn-primary" %>
<% end %>

app/views/flats/show.html.erb
  <h2><%= @flat.name %></h2>
  <p><%= @flat.address %></p>
  <p><%= @flat.description %></p>
  <span><%= @flat.price_per_night %></span>
  <span><%= @flat.number_of_guests %></span>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>